user:
  jay:
    username: 周杰伦
    password: 1234abcd!
  william:
    username: william
    password: 1234abcd!
  failure:
    username: william
    password: william
#基准地址
url: http://www.tcpjwtester.top

mysql:
  db: trading_system
  host: 192.168.254.140
  password: william
  port: 3306
  user: root